# Generated by Django 5.2.2 on 2025-06-05 08:39

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [
        VectorExtension()
    ]
