# Generated by Django 5.2.2 on 2025-06-05 13:41

from django.db import migrations
import numpy as np

def add_img_embeddings(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    embeds = np.load("/home/ec2-user/backend/api/embeddings.npy")
    Embedding = apps.get_model("api", "Embedding")
    for i, embed in enumerate(embeds):
        e = Embedding(embedding=embed, img_id=i)
        e.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_img_embeddings),
    ]
