# Generated by Django 5.2.2 on 2025-06-05 13:41

from django.db import migrations
import numpy as np

# Data migration that saves the image embeddings to the database

def add_img_embeddings(apps, schema_editor):
    embeds = np.load("./api/embeddings.npy")
    Embedding = apps.get_model("api", "Embedding")
    for i, embed in enumerate(embeds):
        e = Embedding(embedding=embed, img_id=i)
        e.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_img_embeddings),
    ]
